Sa openshift
cockroachdb/cockroach-operator pull request #269
Opened 2021-01-04 19:35 UTC by alinadonisa

2021-01-14 18:37 UTC, chrislovecnm requested changes
Looks good, just nitpicks

2021-01-14 18:37 UTC, chrislovecnm commented on pkg/condition/condition.go
> +func SetOperatorCondTrue(ctype api.ClusterConditionType, status *api.CrdbClusterStatus, now metav1.Time) {
Need godoc

2021-01-14 18:37 UTC, chrislovecnm commented on pkg/controller/cluster_controller.go
> +		//return requeueIfError(err)
remove dead code

2021-01-14 18:37 UTC, chrislovecnm commented on pkg/features/operator_features.go
> +	Upgrade:           {Default: true, PreRelease: featuregate.Alpha},
@alinadonisa can we deco Upgrade and Enable the others?  I do not want to push a PR that will conflict with yours

2021-01-14 18:37 UTC, chrislovecnm commented on test-registry.yaml
> +  image: quay.io/alinalion/cockroachdb-operator-index:1.1.21
can we do a placeholder here?

2021-01-20 16:56 UTC, chrisseto approved these changes
LGTM with the smallest if nits.

2021-01-20 16:56 UTC, chrisseto commented on pkg/testutil/fake.go
> +	// panic("implement me")
nit: remove the commented out panic line.

2021-01-20 17:11 UTC, chrisseto approved these changes

2021-01-20 22:04 UTC, chrislovecnm approved these changes

2021-01-22 16:52 UTC, chrislovecnm approved these changes

2021-01-22 16:52 UTC, merged