Bazel Changes for loading order and update
cockroachdb/cockroach-operator pull request #395
Opened 2021-03-31 17:41 UTC by chrislovecnm

2021-03-31 20:49 UTC, rail commented
This also fixes the macos issue, no more `sudo` \o/

2021-03-31 21:01 UTC, keith-mcclellan requested changes
the only real issue here is that something collapsed all the description fields in the CRD into one line and thats going to break the yaml linter that the openshift CI uses.  I wouldn't mind a slightly more verbose comment on line 9 of WORKSPACE too, but otherwise this looks good.

2021-03-31 21:24 UTC, chrislovecnm commented on config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
> +            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecogni
It is auto generated 🤷🏻‍♂️

2021-03-31 21:24 UTC, chrislovecnm commented on WORKSPACE
> +# TODO update
I missed removing the comment

2021-04-01 14:37 UTC, keith-mcclellan commented on config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
> +            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecogni
guess we'll see then, may have to come back to this later

2021-04-01 14:38 UTC, keith-mcclellan approved these changes
LGTM

2021-04-01 14:39 UTC, merged