Rolling restart e2e test
cockroachdb/cockroach-operator pull request #488
Opened 2021-05-06 03:08 UTC by udnay

Testing the rolling restart functionality with e2e test. Validates that
the pods at the end of the test all have a newer timestamp than when the
cluster was initialized.

2021-05-17 21:18 UTC, keith-mcclellan requested changes
There could be other items but I noticed a few spots where I'd expect this to fall over, particularly after we merge Alina's enhanced health check PR

2021-05-17 21:18 UTC, keith-mcclellan commented on e2e/e2e_test.go
> +		WithImage("cockroachdb/cockroach:v20.2.5").
We need an enhancement to the testing framework that pulls this from a central place we can keep up to date.  There are relatively few tests where we should be pinning to specific releases and those are largely around upgrades

2021-05-17 21:18 UTC, keith-mcclellan commented on e2e/e2e_test.go
> +				RequireClusterToBeReadyEventuallyTimeout(t, sb, builder, 500*time.Second)
I think your timeout here will be too short if we merge the safer restart code Alina is working on.  This is a great reason why we need to do a better job parallelizing these test cases.

2021-05-17 21:18 UTC, keith-mcclellan commented on e2e/e2e_test.go
> +				err = wait.Poll(10*time.Second, 500*time.Second, func() (done bool, err error) {
I think this is likely to fail once we add the enhanced restart logic because of a timeout issue

2021-07-12 13:58 UTC, udnay commented
Going to close this as we test restart a lot implicitly already and our e2e tests need some rethinking

2021-07-12 13:58 UTC, closed without merging