Decommission needs to run first
cockroachdb/cockroach-operator pull request #513
Opened 2021-05-19 16:01 UTC by keith-mcclellan

Adjusting the order that the actors run to execute Decommission first so that upgrade doesn't interrupt it.

2021-05-19 17:03 UTC, chrislovecnm commented on pkg/actor/actor.go
> -	decommission := newDecommission(scheme, cl, config)
This line does not need to change. It is the order in the slice that matters

2021-05-19 17:05 UTC, chrislovecnm commented on pkg/actor/actor.go
> +		decommission,
This is where it needed to change 😀 - this is correct

2021-05-19 19:31 UTC, udnay requested changes
Change looks ok to me, but can you fix up the commit history so we keep master clean?

The other thing, should the `Handle` functions be more restrictive to make sure this type of thing doesn't happen again?

2021-05-19 20:37 UTC, keith-mcclellan commented
> Change looks ok to me, but can you fix up the commit history so we keep master clean?
> 

Yeah I got into weird rebase hell, I'll get the commit history cleaned up tomorrow.

2021-05-20 13:26 UTC, keith-mcclellan commented
> The other thing, should the `Handle` functions be more restrictive to make sure this type of thing doesn't happen again?
@chrislovecnm can you chime in here? I would assume the webhooks from the refactor would stop this from happening in the future

2021-05-20 13:30 UTC, udnay commented
Are there times when we want multiple actors to fire for a single event? I guess restart?

2021-05-20 13:46 UTC, closed without merging