Slight refactor of part of e2e decommission test
cockroachdb/cockroach-operator pull request #677
Opened 2021-08-18 22:46 UTC by davidwding

As suggested in https://github.com/cockroachdb/cockroach-operator/issues/631, the PVC check within the decommission e2e test has been slightly refactored to untangle fetching the PVCs and running the test logic itself.

The important part of this PR is in the `RequireNumberOfPVCs` func in require.go; the rest is minor spelling fixes I encountered while reading through / running the code, or auto-formatting applied by crlfmt.

This PR does not also refactor `RequirePVCToResize` within the pvcresize e2e test because I haven't figured out how to actually run that test yet.

2021-08-18 22:46 UTC, cockroach-teamcity commented
[![CLA assistant check](https://cla.crdb.dev/pull/badge/not_signed)](https://cla.crdb.dev/cockroachdb/cockroach-operator?pullRequest=677) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach-operator?pullRequest=677) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach-operator?pullRequest=677) it.</sub>

2021-08-19 15:28 UTC, chrislovecnm commented
@davidwding RequirePVCToResize has to run on GKE, since kind and other platforms do not support resizing PVCs.  Take a look at the e2e test for gke in the Makefile

2021-08-19 16:03 UTC, chrislovecnm requested changes
Mostly nit picks.  I appreciate you doing spelling fixes as well, but next time can we please do them in a different PR, that way we ensure that the PR does not change code funcationality.

2021-08-19 17:59 UTC, davidwding reviewed
Noted about keeping spelling/style changes in separate PRs for more cohesion within one PR; will be more diligent about that

2021-08-19 17:59 UTC, davidwding commented on pkg/testutil/require.go
> +func RequireClusterToBeReadyEventuallyTimeout(
I think this was done by our internal formatter `crlfmt`, which I was told to have my code editor auto-run every time I save. It seems like it enforces style beyond what `gofmt` recommends. Not sure if you have access to this but there's more info here: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072641/What+is+a+Good+CockroachDB+PR#WhatisaGoodCockroachDBPR-Adherencetothecodingstyle

2021-08-19 17:59 UTC, davidwding commented on pkg/testutil/require.go
> +func RequireNumberOfPVCs(
Can you elaborate? It's also iterating over the list of PVCs and checking that the quantity matches the input argument, so it still seems right to me.

2021-08-19 17:59 UTC, davidwding commented on go.sum
> -bazil.org/fuse v0.0.0-20180421153158-65cc252bf669 h1:FNCRpXiquG1aoyqcIWVFmpTSKVcx2bQD38uZZeGtdlw=
Sure

2021-08-19 18:04 UTC, chrislovecnm commented on pkg/testutil/require.go
> +func RequireClusterToBeReadyEventuallyTimeout(
Cool! But that is for crdb, not the operator. We have never used the tool on this project. @udnay should we use this tool now?

2021-08-19 18:05 UTC, chrislovecnm commented on pkg/testutil/require.go
> +func RequireNumberOfPVCs(
I might not be reading the diff correctly. I will take a look in a bit

2021-08-19 18:17 UTC, udnay commented on pkg/testutil/require.go
> +func RequireClusterToBeReadyEventuallyTimeout(
Let's not use it for now @davidwding and we can discuss as a team. A lot of the docs are CRDB specific and I don't think that we need to adhere to all the same standards for now.

2021-08-19 18:19 UTC, davidwding commented on pkg/testutil/require.go
> +func RequireClusterToBeReadyEventuallyTimeout(
SGTM

2021-08-19 18:49 UTC, pseudomuto submitted a review, later dismissed

2021-08-23 14:42 UTC, pseudomuto approved these changes

2021-08-23 15:16 UTC, merged