Added Taint and Tolerations support in crdb cluster #695
cockroachdb/cockroach-operator pull request #702
Opened 2021-09-09 13:58 UTC by abhishekdwivedi3060

Closes #695 
* Added Taint and Tolerations support in crdb cluster
* Added the new API field  "tolerations". tolerations is a []corev1.Toleration struct which allows the user to set tolerations for pod scheduling onto dedicated nodes
* Modified existing unit test for this change

2021-09-09 13:58 UTC, cockroach-teamcity commented
[![CLA assistant check](https://cla.crdb.dev/pull/badge/not_signed)](https://cla.crdb.dev/cockroachdb/cockroach-operator?pullRequest=702) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach-operator?pullRequest=702) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach-operator?pullRequest=702) it.</sub>

2021-09-11 00:01 UTC, chrislovecnm requested changes
Looks good, if you can back out the changes to the files that are not needed in this PR please

2021-09-11 02:14 UTC, abhishekdwivedi3060 commented on apis/v1alpha1/cluster_types.go
> +
Done, removed new lines

2021-09-11 02:20 UTC, abhishekdwivedi3060 commented on pkg/actor/actor.go
> +
Done

2021-09-13 18:43 UTC, pseudomuto reviewed
Code LGTM 👍 

Do we have a test to prove this does what we intend it to? I understand tolerations are a builtin, just wondering if we should update the e2e tests somehow to make sure this feature works.

2021-09-13 18:59 UTC, abhishekdwivedi3060 commented
There is unit-test to check if Tolerations field value is propagated to actual sts pod.
I don't think there is any e2e for existing fields like `AffinityRules`
As you mentioned these functionalities are built it, so not sure how useful that will be to add e2e for those

2021-09-13 19:02 UTC, pseudomuto commented
> As you mentioned these functionalities are built it, so not sure how useful that will be to add e2e for those

Ok, that's kinda fair. I think we should at least test it though, even if it's manually. Just to be sure that it works, like that we set all the fields correctly and K8s does what we expect.

2021-09-13 19:30 UTC, chrislovecnm approved these changes

2021-09-13 20:05 UTC, merged