Added nodeSelector support
cockroachdb/cockroach-operator pull request #769
Opened 2021-10-08 15:36 UTC by cin

Added support for nodeSelectors to the CRD.

Resolves #762

2021-10-08 15:36 UTC, cockroach-teamcity commented
[![CLA assistant check](https://cla.crdb.dev/pull/badge/not_signed)](https://cla.crdb.dev/cockroachdb/cockroach-operator?pullRequest=769) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach-operator?pullRequest=769) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach-operator?pullRequest=769) it.</sub>

2021-10-08 18:03 UTC, chrislovecnm reviewed
Thanks for the PR.  Some comments for you.

2021-10-08 19:31 UTC, cin commented on pkg/resource/statefulset.go
> +			NodeSelector:                  b.Spec().NodeSelector,
Just to be clear, do you mean something like:
```go
	if b.Spec().NodeSelector != nil && len(b.Spec().NodeSelector) > 0 {
		pod.Spec.NodeSelector = b.Spec().NodeSelector
	}
```

Or do you mean put this behind a feature gate?

2021-10-08 19:33 UTC, chrislovecnm commented on pkg/resource/statefulset.go
> +			NodeSelector:                  b.Spec().NodeSelector,
The if statement is perfect

2021-10-08 19:36 UTC, cin commented on examples/3-nodes-insecure-with-nodeselector.yaml
> +  nodes: 3
Good points. I didn't know about the example templates. I did as you suggested and regenerated the templates. LMK if there's anything else to do in this regard.

2021-10-08 20:18 UTC, chrislovecnm approved these changes
LGTM

2021-10-08 20:42 UTC, pseudomuto requested changes

2021-10-08 20:42 UTC, pseudomuto commented on config/manager/patches/image.yaml
> +          image: cockroachdb/cockroach-operator:2.2.1
This shouldn't have changed. Did this happen when you ran make/gen-templates?

2021-10-13 03:39 UTC, pseudomuto approved these changes

2021-10-13 18:23 UTC, cin commented
I rebased and squashed all the intermittent commits. Should be good to go now.

2021-10-13 19:53 UTC, merged